<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>
  <Target Name="Create bundles" BeforeTargets="BeforeBuild">
    <Exec Command="npm install" WorkingDirectory="npmjs" />
    <Exec Command="npm run build" WorkingDirectory="npmjs"/>
  </Target>  
  <ItemGroup>
    <ProjectReference Include="..\WebSocketCommon\WebSocketCommon.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Logging.Memory" Version="3.1.0" />
    <PackageReference Include="ReactiveProperty" Version="9.8.0" />
  </ItemGroup>
</Project>
